require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/films", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Film. As you add validations to Film, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Film.create! valid_attributes
      get films_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      film = Film.create! valid_attributes
      get film_url(film)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_film_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      film = Film.create! valid_attributes
      get edit_film_url(film)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Film" do
        expect {
          post films_url, params: { film: valid_attributes }
        }.to change(Film, :count).by(1)
      end

      it "redirects to the created film" do
        post films_url, params: { film: valid_attributes }
        expect(response).to redirect_to(film_url(Film.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Film" do
        expect {
          post films_url, params: { film: invalid_attributes }
        }.to change(Film, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post films_url, params: { film: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested film" do
        film = Film.create! valid_attributes
        patch film_url(film), params: { film: new_attributes }
        film.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the film" do
        film = Film.create! valid_attributes
        patch film_url(film), params: { film: new_attributes }
        film.reload
        expect(response).to redirect_to(film_url(film))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        film = Film.create! valid_attributes
        patch film_url(film), params: { film: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested film" do
      film = Film.create! valid_attributes
      expect {
        delete film_url(film)
      }.to change(Film, :count).by(-1)
    end

    it "redirects to the films list" do
      film = Film.create! valid_attributes
      delete film_url(film)
      expect(response).to redirect_to(films_url)
    end
  end
end
