default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RatingFilms_development

test:
  <<: *default
  database: RatingFilms_test

production:
  <<: *default
  database: RatingFilms_production
  username: RatingFilms
  password: <%= ENV["RATINGFILMS_DATABASE_PASSWORD"] %>
